### ISSUE TITLE
Terminate: quality score larger than 63

### ISSUE THREAD

**Issue by Timothy-WANG** [bioinfologics/w2rap-contigger#23]
Hi, recently, the program has stopped with the following error, so shall I trying to change the reads score ?
Meanwhile, how to set up the K value if the reads score is 100bp?
Thanks!
--== Step 1: Reading input files ==--
Thu Apr 20 22:48:23 2017: finding input files
Thu Apr 20 22:48:23 2017: reading 2 files (which may take a while)

Your input reads are funny.  I found a quality score of 66.
The maximum value that I allow is 63.

**Comment by bjclavijo** [comment]
Read length 100bp is probably not going to produce very good results. Check if your fragment size is >250bp, otherwise you may be better off running another assembler. (abyss, maybe?).
Quality of 66 is clearly wrong, so check your files, may it be that these are old illumina files and your quality is on +33 format?
w2rap expects modern illumina data: https://en.wikipedia.org/wiki/FASTQ_format#Quality

**Comment by bjclavijo** [comment]
Closing this as it has been inactive for 2 years
